### ISSUE TITLE
cannot collapse back

### ISSUE THREAD

**Issue by machinezhou** [Chen-Sir/ExpandableTextView#2]
hi, sir:
I use the code follow your instruction
layout:
`
  <com.zhjs.sucker.ui.views.ExpandableTextView
      android:id="@+id/tv"
      android:layout_width="match_parent"
      android:layout_height="wrap_content"
      app:contentTextColor="@color/colorPrimary"
      app:maxCollapsedLines="3">
  </com.zhjs.sucker.ui.views.ExpandableTextView>`

activity:
`
    tv.setText("标签作为一个版本号，随着标签指针上的每一次CAS运算而增加，并且只增不减"
        + "。一旦需要从容器中非物理地移除某个元素，就应将其放入一个"
        + "盛放空闲元素的列表中。在空闲元素列表中，逻辑删除的元素完全有可能被"
        + "再次调用。因为是无锁数据结构，一个线程删除X元素，另外一个线程依然可以持"
        + "有标签指针的本地副本，并指向元素字段。因此需要一个针对每种T类型的空闲元素列表"
        + "。多数情况下，将元素放入空闲列表中，意味着调用这个T类型数据的析构函数是非法的（考"
        + "虑到并行访问，在析构函数运算的过程中，其它线程是可以读到此元素的数据）。");`

environment:
device:nexus 5
android:6.0

but it cannot collapse back.

**Comment by machinezhou** [comment]
Turns out the reason is ExpandableTextView has relativelayout parent and ExpandableTextView is the only child.

**Comment by Chen-Sir** [comment]
@machinezhou 嗯，不好意思。这几天较忙。没看到你发的issue，抱歉。  我先去看看这个问题

**Comment by Chen-Sir** [comment]
@machinezhou 您的意思是下面这样布局吗？我刚刚试了一下，可以收起和展开啊。


       <RelativeLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content">

            <me.chensir.expandabletextview.ExpandableTextView
                android:id="@+id/tv3"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:layout_marginTop="8dp"
                app:DrawableAndTextGravity="right"
                app:collapseDrawable="@mipmap/icon_collapsed"
                app:contentTextColor="@color/colorPrimaryDark"
                app:expandCollapseTextColor="@color/colorAccent"
                app:expandDrawable="@mipmap/icon_expand"
                app:expandText="更多"
                app:maxCollapsedLines="6">

            </me.chensir.expandabletextview.ExpandableTextView>

        </RelativeLayout>
