### ISSUE TITLE
height calculation problem in both English and Chinese

### ISSUE THREAD

**Issue by JackyBower** [Chen-Sir/ExpandableTextView#3]
private static int getRealTextViewHeight(@NonNull TextView textView) {
        int textHeight = textView.getLayout().getLineTop(textView.getLineCount());
        int padding = textView.getCompoundPaddingTop() + textView.getCompoundPaddingBottom();
        return textHeight + padding;
    }

**Comment by Chen-Sir** [comment]
Do you mean this method is wrong ?

**Comment by JackyBower** [comment]
![qq 20170111132100](https://cloud.githubusercontent.com/assets/7868144/21836547/f6684bd0-d800-11e6-9d8d-037957f9dd88.png)
![qq 20170111132133](https://cloud.githubusercontent.com/assets/7868144/21836548/f67244e6-d800-11e6-9fdf-68b9b7df6b1b.png)
