### ISSUE TITLE
换行符一多就要出问题

### ISSUE THREAD

**Issue by cococa** [Chen-Sir/ExpandableTextView#6]
<item>"\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nasdasdasdasd\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n"</item>

list 中显示上面的文字，就会出现错误

**Comment by Chen-Sir** [comment]
我也试过了，但没发现问题
