### ISSUE TITLE
当expandabletextview和其他组件包裹在一个linearlayout中horizontal排列时，失效

### ISSUE THREAD

**Issue by brandlee** [Chen-Sir/ExpandableTextView#8]
需求是将expandabletextview和一个textview包裹在一个linearlayout中，此时按照从左到右的方式排列，会发现expandabletextview失效，没有收起展开的功能了，麻烦请教一下这个问题

**Comment by ImportEffort** [comment]
我也是的

**Comment by Chen-Sir** [comment]
非常抱歉。由于平时精力有限，该库已经不再维护。
源代码非常简单，如果你们遇到什么问题，直接看源码解决。
